### ISSUE TITLE
False значения булевых переменных не подставляются в манифесты

### ISSUE THREAD

**Issue by sgolod** [flant/helm-apps#21]
Имеем следующее описание приложений:
helm-apps-defaults.yaml:
```
apps-defaults:
  enabled: true

apps-default-library-app:
  _include: ["apps-defaults"]

apps-stateless-defaultApp:
  _include: ["apps-default-library-app"]
  revisionHistoryLimit: 3
```
values.yaml:
```
global:
  _includes:
    _include_from_file: helm-apps-defaults.yaml

# ...
apps-stateless:
  admin-backend:
    _include: ["apps-stateless-defaultApp"]
    replicas: 1
    automountServiceAccountToken: false
```

Сгенерированный манифест для Deployment:
```
# Source: tracking-admin/templates/init-helm-apps.yaml
# Helm Apps Library: apps-stateless.admin-backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "admin-backend"
...
spec:
  ...
  template:
    spec:
      ...
      automountServiceAccountToken:
```

Ожидаемое поведение: `automountServiceAccountToken` в манифесте должен получить значение `false` вместо пустого значения.
При указании значения `true` в values.yaml значение `true` **корректно** подставляется в манифест.

Версии приложений:
```
werf: v1.2.188+fix1
helm-apps: 1.2.9
```
